services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: logsuser
      POSTGRES_PASSWORD: logspass
      POSTGRES_DB: logsdb
    ports:
      - "5432:5432"
    volumes:
      - ./dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
      - pgdata:/var/lib/postgresql/data

  fluent-bit:
    build: ./fluent-bit
    container_name: fluent-bit
    env_file: .env
    ports:
      - "24224:24224"
    depends_on:
      - api

  # -------------------------------------------
  # Dummy app — simulates a friend's application
  # Logs JSON to stdout, Docker ships it to Fluent Bit
  # -------------------------------------------
  dummy-app:
    build: ./dummy-app
    container_name: dummy-app
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "dummy-app"
    depends_on:
      - fluent-bit

  consumer:
    build: ./consumer
    container_name: consumer
    env_file: .env
    depends_on:
      - redis
      - postgres

  api:
    build: ./api
    container_name: api
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  pgdata:
